const text1 = document.getElementById('text1');
const text2 = document.getElementById('text2');
const text3 = document.getElementById('text3');
const text4 = document.getElementById('text4');
const text5 = document.getElementById('text5');
const text6 = document.getElementById('text6');
const text7 = document.getElementById('text7');
const text8 = document.getElementById('text8');
const text9 = document.getElementById('text9');
const text10 = document.getElementById('text10');
const text11 = document.getElementById('text11');
const text12 = document.getElementById('text12');
const text13 = document.getElementById('text13');
const text14 = document.getElementById('text14');
const text15 = document.getElementById('text15');
const text16 = document.getElementById('text16');
const text17 = document.getElementById('text17');
const text18 = document.getElementById('text18');
const text19 = document.getElementById('text19');
const text20 = document.getElementById('text20');
const text21 = document.getElementById('text21');
const text22 = document.getElementById('text22');
const text23 = document.getElementById('text23');
const text24 = document.getElementById('text24');
const text25 = document.getElementById('text25');
const text26 = document.getElementById('text26');
const text27 = document.getElementById('text27');
const text28 = document.getElementById('text28');
const text29 = document.getElementById('text29');
const text30 = document.getElementById('text30');
const text31 = document.getElementById('text31');
const text32 = document.getElementById('text32');
const text33 = document.getElementById('text33');
const text34 = document.getElementById('text34');
const text35 = document.getElementById('text35');
const text36 = document.getElementById('text36');
const text37 = document.getElementById('text37');
const text38 = document.getElementById('text38');
const text39 = document.getElementById('text39');
const text40 = document.getElementById('text40');
const text41 = document.getElementById('text41');
const text42 = document.getElementById('text42');
const text43 = document.getElementById('text43');
const text44 = document.getElementById('text44');
const text45 = document.getElementById('text45');
const text46 = document.getElementById('text46');
const text47 = document.getElementById('text47');
const text48 = document.getElementById('text48');
const text49 = document.getElementById('text49');
const text50 = document.getElementById('text50');
const text51 = document.getElementById('text51');
const text52 = document.getElementById('text52');
const text53 = document.getElementById('text53');
const text54 = document.getElementById('text54');
const text55 = document.getElementById('text55');
const text56 = document.getElementById('text56');
const text57 = document.getElementById('text57');
const text58 = document.getElementById('text58');
const text59 = document.getElementById('text59');
const text60 = document.getElementById('text60');
const text61 = document.getElementById('text61');
const text62 = document.getElementById('text62');
const text63 = document.getElementById('text63');
const text64 = document.getElementById('text64');
const text65 = document.getElementById('text65');
const text66 = document.getElementById('text66');
const text67 = document.getElementById('text67');
const text68 = document.getElementById('text68');
const text69 = document.getElementById('text69');
const text70 = document.getElementById('text70');
const text71 = document.getElementById('text71');
const text72 = document.getElementById('text72');
const text73 = document.getElementById('text73');
const text74 = document.getElementById('text74');
const text75 = document.getElementById('text75');
const text76 = document.getElementById('text76');
const text77 = document.getElementById('text77');
const text78 = document.getElementById('text78');
const text79 = document.getElementById('text79');
const text80 = document.getElementById('text80');
const text81 = document.getElementById('text81');
const text82 = document.getElementById('text82');
const text83 = document.getElementById('text83');
const text84 = document.getElementById('text84');
const text85 = document.getElementById('text85');
const text86 = document.getElementById('text86');
const text87 = document.getElementById('text87');
const text88 = document.getElementById('text88');
const text89 = document.getElementById('text89');
const text90 = document.getElementById('text90');
const text91 = document.getElementById('text91');
const text92 = document.getElementById('text92');
const text93 = document.getElementById('text93');
const text94 = document.getElementById('text94');
const text95 = document.getElementById('text95');
const text96 = document.getElementById('text96');
const text97 = document.getElementById('text97');
const text98 = document.getElementById('text98');
const text99 = document.getElementById('text99');
const text100 = document.getElementById('text100');
const text101 = document.getElementById('text101');
const text102 = document.getElementById('text102');
const text103 = document.getElementById('text103');
const text104 = document.getElementById('text104');
const text105 = document.getElementById('text105');
const text106 = document.getElementById('text106');
const text107 = document.getElementById('text107');
const text108 = document.getElementById('text108');
const text109 = document.getElementById('text109');



text1.addEventListener('mouseenter', function() {text1.classList.add('active');});
text1.addEventListener('mouseleave', function() {text1.classList.remove('active');});
text2.addEventListener('mouseenter', function() {text2.classList.add('active');});
text2.addEventListener('mouseleave', function() {text2.classList.remove('active');});
text3.addEventListener('mouseenter', function() {text3.classList.add('active');});
text3.addEventListener('mouseleave', function() {text3.classList.remove('active');});
text4.addEventListener('mouseenter', function() {text4.classList.add('active');});
text4.addEventListener('mouseleave', function() {text4.classList.remove('active');});
text5.addEventListener('mouseenter', function() {text5.classList.add('active');});
text5.addEventListener('mouseleave', function() {text5.classList.remove('active');});
text6.addEventListener('mouseenter', function() {text6.classList.add('active');});
text6.addEventListener('mouseleave', function() {text6.classList.remove('active');});
text7.addEventListener('mouseenter', function() {text7.classList.add('active');});
text7.addEventListener('mouseleave', function() {text7.classList.remove('active');});
text8.addEventListener('mouseenter', function() {text8.classList.add('active');});
text8.addEventListener('mouseleave', function() {text8.classList.remove('active');});
text9.addEventListener('mouseenter', function() {text9.classList.add('active');});
text9.addEventListener('mouseleave', function() {text9.classList.remove('active');});
text10.addEventListener('mouseenter', function() {text10.classList.add('active');});
text10.addEventListener('mouseleave', function() {text10.classList.remove('active');});
text11.addEventListener('mouseenter', function() {text11.classList.add('active');});
text11.addEventListener('mouseleave', function() {text11.classList.remove('active');});
text12.addEventListener('mouseenter', function() {text12.classList.add('active');});
text12.addEventListener('mouseleave', function() {text12.classList.remove('active');});
text13.addEventListener('mouseenter', function() {text13.classList.add('active');});
text13.addEventListener('mouseleave', function() {text13.classList.remove('active');});
text14.addEventListener('mouseenter', function() {text14.classList.add('active');});
text14.addEventListener('mouseleave', function() {text14.classList.remove('active');});
text15.addEventListener('mouseenter', function() {text15.classList.add('active');});
text15.addEventListener('mouseleave', function() {text15.classList.remove('active');});
text16.addEventListener('mouseenter', function() {text16.classList.add('active');});
text16.addEventListener('mouseleave', function() {text16.classList.remove('active');});
text17.addEventListener('mouseenter', function() {text17.classList.add('active');});
text17.addEventListener('mouseleave', function() {text17.classList.remove('active');});
text18.addEventListener('mouseenter', function() {text18.classList.add('active');});
text18.addEventListener('mouseleave', function() {text18.classList.remove('active');});
text19.addEventListener('mouseenter', function() {text19.classList.add('active');});
text19.addEventListener('mouseleave', function() {text19.classList.remove('active');});
text20.addEventListener('mouseenter', function() {text20.classList.add('active');});
text20.addEventListener('mouseleave', function() {text20.classList.remove('active');});
text21.addEventListener('mouseenter', function() {text21.classList.add('active');});
text21.addEventListener('mouseleave', function() {text21.classList.remove('active');});
text22.addEventListener('mouseenter', function() {text22.classList.add('active');});
text22.addEventListener('mouseleave', function() {text22.classList.remove('active');});
text23.addEventListener('mouseenter', function() {text23.classList.add('active');});
text23.addEventListener('mouseleave', function() {text23.classList.remove('active');});
text24.addEventListener('mouseenter', function() {text24.classList.add('active');});
text24.addEventListener('mouseleave', function() {text24.classList.remove('active');});
text25.addEventListener('mouseenter', function() {text25.classList.add('active');});
text25.addEventListener('mouseleave', function() {text25.classList.remove('active');});
text26.addEventListener('mouseenter', function() {text26.classList.add('active');});
text26.addEventListener('mouseleave', function() {text26.classList.remove('active');});
text27.addEventListener('mouseenter', function() {text27.classList.add('active');});
text27.addEventListener('mouseleave', function() {text27.classList.remove('active');});
text28.addEventListener('mouseenter', function() {text28.classList.add('active');});
text28.addEventListener('mouseleave', function() {text28.classList.remove('active');});
text29.addEventListener('mouseenter', function() {text29.classList.add('active');});
text29.addEventListener('mouseleave', function() {text29.classList.remove('active');});
text30.addEventListener('mouseenter', function() {text30.classList.add('active');});
text30.addEventListener('mouseleave', function() {text30.classList.remove('active');});
text31.addEventListener('mouseenter', function() {text31.classList.add('active');});
text31.addEventListener('mouseleave', function() {text31.classList.remove('active');});
text32.addEventListener('mouseenter', function() {text32.classList.add('active');});
text32.addEventListener('mouseleave', function() {text32.classList.remove('active');});
text33.addEventListener('mouseenter', function() {text33.classList.add('active');});
text33.addEventListener('mouseleave', function() {text33.classList.remove('active');});
text34.addEventListener('mouseenter', function() {text34.classList.add('active');});
text34.addEventListener('mouseleave', function() {text34.classList.remove('active');});
text35.addEventListener('mouseenter', function() {text35.classList.add('active');});
text35.addEventListener('mouseleave', function() {text35.classList.remove('active');});
text36.addEventListener('mouseenter', function() {text36.classList.add('active');});
text36.addEventListener('mouseleave', function() {text36.classList.remove('active');});
text37.addEventListener('mouseenter', function() {text37.classList.add('active');});
text37.addEventListener('mouseleave', function() {text37.classList.remove('active');});
text38.addEventListener('mouseenter', function() {text38.classList.add('active');});
text38.addEventListener('mouseleave', function() {text38.classList.remove('active');});
text39.addEventListener('mouseenter', function() {text39.classList.add('active');});
text39.addEventListener('mouseleave', function() {text39.classList.remove('active');});
text40.addEventListener('mouseenter', function() {text40.classList.add('active');});
text40.addEventListener('mouseleave', function() {text40.classList.remove('active');});
text41.addEventListener('mouseenter', function() {text41.classList.add('active');});
text41.addEventListener('mouseleave', function() {text41.classList.remove('active');});
text42.addEventListener('mouseenter', function() {text42.classList.add('active');});
text42.addEventListener('mouseleave', function() {text42.classList.remove('active');});
text43.addEventListener('mouseenter', function() {text43.classList.add('active');});
text43.addEventListener('mouseleave', function() {text43.classList.remove('active');});
text44.addEventListener('mouseenter', function() {text44.classList.add('active');});
text44.addEventListener('mouseleave', function() {text44.classList.remove('active');});
text45.addEventListener('mouseenter', function() {text45.classList.add('active');});
text45.addEventListener('mouseleave', function() {text45.classList.remove('active');});
text46.addEventListener('mouseenter', function() {text46.classList.add('active');});
text46.addEventListener('mouseleave', function() {text46.classList.remove('active');});
text47.addEventListener('mouseenter', function() {text47.classList.add('active');});
text47.addEventListener('mouseleave', function() {text47.classList.remove('active');});
text48.addEventListener('mouseenter', function() {text48.classList.add('active');});
text48.addEventListener('mouseleave', function() {text48.classList.remove('active');});
text49.addEventListener('mouseenter', function() {text49.classList.add('active');});
text49.addEventListener('mouseleave', function() {text49.classList.remove('active');});
text50.addEventListener('mouseenter', function() {text50.classList.add('active');});
text50.addEventListener('mouseleave', function() {text50.classList.remove('active');});
text51.addEventListener('mouseenter', function() {text51.classList.add('active');});
text51.addEventListener('mouseleave', function() {text51.classList.remove('active');});
text52.addEventListener('mouseenter', function() {text52.classList.add('active');});
text52.addEventListener('mouseleave', function() {text52.classList.remove('active');});
text53.addEventListener('mouseenter', function() {text53.classList.add('active');});
text53.addEventListener('mouseleave', function() {text53.classList.remove('active');});
text54.addEventListener('mouseenter', function() {text54.classList.add('active');});
text54.addEventListener('mouseleave', function() {text54.classList.remove('active');});
text55.addEventListener('mouseenter', function() {text55.classList.add('active');});
text55.addEventListener('mouseleave', function() {text55.classList.remove('active');});
text56.addEventListener('mouseenter', function() {text56.classList.add('active');});
text56.addEventListener('mouseleave', function() {text56.classList.remove('active');});
text57.addEventListener('mouseenter', function() {text57.classList.add('active');});
text57.addEventListener('mouseleave', function() {text57.classList.remove('active');});
text58.addEventListener('mouseenter', function() {text58.classList.add('active');});
text58.addEventListener('mouseleave', function() {text58.classList.remove('active');});
text59.addEventListener('mouseenter', function() {text59.classList.add('active');});
text59.addEventListener('mouseleave', function() {text59.classList.remove('active');});
text60.addEventListener('mouseenter', function() {text60.classList.add('active');});
text60.addEventListener('mouseleave', function() {text60.classList.remove('active');});
text61.addEventListener('mouseenter', function() {text61.classList.add('active');});
text61.addEventListener('mouseleave', function() {text61.classList.remove('active');});
text62.addEventListener('mouseenter', function() {text62.classList.add('active');});
text62.addEventListener('mouseleave', function() {text62.classList.remove('active');});
text63.addEventListener('mouseenter', function() {text63.classList.add('active');});
text63.addEventListener('mouseleave', function() {text63.classList.remove('active');});
text64.addEventListener('mouseenter', function() {text64.classList.add('active');});
text64.addEventListener('mouseleave', function() {text64.classList.remove('active');});
text65.addEventListener('mouseenter', function() {text65.classList.add('active');});
text65.addEventListener('mouseleave', function() {text65.classList.remove('active');});
text66.addEventListener('mouseenter', function() {text66.classList.add('active');});
text66.addEventListener('mouseleave', function() {text66.classList.remove('active');});
text67.addEventListener('mouseenter', function() {text67.classList.add('active');});
text67.addEventListener('mouseleave', function() {text67.classList.remove('active');});
text68.addEventListener('mouseenter', function() {text68.classList.add('active');});
text68.addEventListener('mouseleave', function() {text68.classList.remove('active');});
text69.addEventListener('mouseenter', function() {text69.classList.add('active');});
text69.addEventListener('mouseleave', function() {text69.classList.remove('active');});
text70.addEventListener('mouseenter', function() {text70.classList.add('active');});
text70.addEventListener('mouseleave', function() {text70.classList.remove('active');});
text71.addEventListener('mouseenter', function() {text71.classList.add('active');});
text71.addEventListener('mouseleave', function() {text71.classList.remove('active');});
text72.addEventListener('mouseenter', function() {text72.classList.add('active');});
text72.addEventListener('mouseleave', function() {text72.classList.remove('active');});
text73.addEventListener('mouseenter', function() {text73.classList.add('active');});
text73.addEventListener('mouseleave', function() {text73.classList.remove('active');});
text74.addEventListener('mouseenter', function() {text74.classList.add('active');});
text74.addEventListener('mouseleave', function() {text74.classList.remove('active');});
text75.addEventListener('mouseenter', function() {text75.classList.add('active');});
text75.addEventListener('mouseleave', function() {text75.classList.remove('active');});
text76.addEventListener('mouseenter', function() {text76.classList.add('active');});
text76.addEventListener('mouseleave', function() {text76.classList.remove('active');});
text77.addEventListener('mouseenter', function() {text77.classList.add('active');});
text77.addEventListener('mouseleave', function() {text77.classList.remove('active');});
text78.addEventListener('mouseenter', function() {text78.classList.add('active');});
text78.addEventListener('mouseleave', function() {text78.classList.remove('active');});
text79.addEventListener('mouseenter', function() {text79.classList.add('active');});
text79.addEventListener('mouseleave', function() {text79.classList.remove('active');});
text80.addEventListener('mouseenter', function() {text80.classList.add('active');});
text80.addEventListener('mouseleave', function() {text80.classList.remove('active');});
text81.addEventListener('mouseenter', function() {text81.classList.add('active');});
text81.addEventListener('mouseleave', function() {text81.classList.remove('active');});
text82.addEventListener('mouseenter', function() {text82.classList.add('active');});
text82.addEventListener('mouseleave', function() {text82.classList.remove('active');});
text83.addEventListener('mouseenter', function() {text83.classList.add('active');});
text83.addEventListener('mouseleave', function() {text83.classList.remove('active');});
text84.addEventListener('mouseenter', function() {text84.classList.add('active');});
text84.addEventListener('mouseleave', function() {text84.classList.remove('active');});
text85.addEventListener('mouseenter', function() {text85.classList.add('active');});
text85.addEventListener('mouseleave', function() {text85.classList.remove('active');});
text86.addEventListener('mouseenter', function() {text86.classList.add('active');});
text86.addEventListener('mouseleave', function() {text86.classList.remove('active');});
text87.addEventListener('mouseenter', function() {text87.classList.add('active');});
text87.addEventListener('mouseleave', function() {text87.classList.remove('active');});
text88.addEventListener('mouseenter', function() {text88.classList.add('active');});
text88.addEventListener('mouseleave', function() {text88.classList.remove('active');});
text89.addEventListener('mouseenter', function() {text89.classList.add('active');});
text89.addEventListener('mouseleave', function() {text89.classList.remove('active');});
text90.addEventListener('mouseenter', function() {text90.classList.add('active');});
text90.addEventListener('mouseleave', function() {text90.classList.remove('active');});
text91.addEventListener('mouseenter', function() {text91.classList.add('active');});
text91.addEventListener('mouseleave', function() {text91.classList.remove('active');});
text92.addEventListener('mouseenter', function() {text92.classList.add('active');});
text92.addEventListener('mouseleave', function() {text92.classList.remove('active');});
text93.addEventListener('mouseenter', function() {text93.classList.add('active');});
text93.addEventListener('mouseleave', function() {text93.classList.remove('active');});
text94.addEventListener('mouseenter', function() {text94.classList.add('active');});
text94.addEventListener('mouseleave', function() {text94.classList.remove('active');});
text95.addEventListener('mouseenter', function() {text95.classList.add('active');});
text95.addEventListener('mouseleave', function() {text95.classList.remove('active');});
text96.addEventListener('mouseenter', function() {text96.classList.add('active');});
text96.addEventListener('mouseleave', function() {text96.classList.remove('active');});
text97.addEventListener('mouseenter', function() {text97.classList.add('active');});
text97.addEventListener('mouseleave', function() {text97.classList.remove('active');});
text98.addEventListener('mouseenter', function() {text98.classList.add('active');});
text98.addEventListener('mouseleave', function() {text98.classList.remove('active');});
text99.addEventListener('mouseenter', function() {text99.classList.add('active');});
text99.addEventListener('mouseleave', function() {text99.classList.remove('active');});
text100.addEventListener('mouseenter', function() {text100.classList.add('active');});
text100.addEventListener('mouseleave', function() {text100.classList.remove('active');});
text101.addEventListener('mouseenter', function() {text101.classList.add('active');});
text101.addEventListener('mouseleave', function() {text101.classList.remove('active');});
text102.addEventListener('mouseenter', function() {text102.classList.add('active');});
text102.addEventListener('mouseleave', function() {text102.classList.remove('active');});
text103.addEventListener('mouseenter', function() {text103.classList.add('active');});
text103.addEventListener('mouseleave', function() {text103.classList.remove('active');});
text104.addEventListener('mouseenter', function() {text104.classList.add('active');});
text104.addEventListener('mouseleave', function() {text104.classList.remove('active');});
text105.addEventListener('mouseenter', function() {text105.classList.add('active');});
text105.addEventListener('mouseleave', function() {text105.classList.remove('active');});
text106.addEventListener('mouseenter', function() {text106.classList.add('active');});
text106.addEventListener('mouseleave', function() {text106.classList.remove('active');});
text107.addEventListener('mouseenter', function() {text107.classList.add('active');});
text107.addEventListener('mouseleave', function() {text107.classList.remove('active');});
text108.addEventListener('mouseenter', function() {text108.classList.add('active');});
text108.addEventListener('mouseleave', function() {text108.classList.remove('active');});
text109.addEventListener('mouseenter', function() {text109.classList.add('active');});
text109.addEventListener('mouseleave', function() {text109.classList.remove('active');});
